/*
 * DO NOT EDIT THIS FILE.  It contains C->PostScript communication
 * functions that were automatically generated from todo_min_cps.cps
 */
#ifndef PSMACROS_H
#include <NeWS/psmacros.h>		/* standard cdef macros */
#endif

#include "todo_min_cps.h"


void cps_set_label ( win, str)
	int win; 
	char *str; 
{
    static unsigned char _CPS_cps_set_label[] = "%s/setlabel%usend ";

  pprintf (PostScript, _CPS_cps_set_label, 18, str, win);
}

void cps_set_footer ( win, left, right)
	int win; 
	char *left; 
	char *right; 
{
    static unsigned char _CPS_cps_set_footer[] = "%s%s/setfooter%usend ";

  pprintf (PostScript, _CPS_cps_set_footer, 21, left, right, win);
}

void cps_label ( win,  tag, str)
	int win; 
	int tag; 
	char *str; 
{
    static unsigned char _CPS_cps_label[] = "/label%usend%d\246\311\265\246\220\246K{\275\220}\246k\246\321";

  pprintf (PostScript, _CPS_cps_label, 29, win, tag);
  if  (ps_checkfor (PostScriptInput, PSIO_WAIT_TAG, tag) > 0)
    pscanf (PostScriptInput, "s", str);
}

void cps_footer ( win,  tag, left, right)
	int win; 
	int tag; 
	char *left; 
	char *right; 
{
    static unsigned char _CPS_cps_footer[] = "/footer%usend%d\246\311\265\246\220\246K{\275\220}\246k\246\321\265\246\220\246K{\275\220}\246k\246\321";

  pprintf (PostScript, _CPS_cps_footer, 43, win, tag);
  if  (ps_checkfor (PostScriptInput, PSIO_WAIT_TAG, tag) > 0)
    pscanf (PostScriptInput, "ss", right, left);
}

void cps_set_named_colors ( obj, fg, bg)
	int obj; 
	char *fg; 
	char *bg; 
{
    static unsigned char _CPS_cps_set_named_colors[] = "/colors%usend %p\265\246\220\246\214{ ColorDict\266\246]\266}\246k\275\266%p\265\246\220\246\214{ ColorDict\266\246]\266}\246k\275\266/setcolors%usend ";

  pprintf (PostScript, _CPS_cps_set_named_colors, 85, obj, bg, fg, obj);
}

void cps_setwindow1 ( t_window1,  tk_window1)
	int t_window1; 
	int tk_window1; 
{
    static unsigned char _CPS_cps_setwindow1[] = "window1%d\246\263/tagnum%d/setproperty window1 send ";

  pprintf (PostScript, _CPS_cps_setwindow1, 46, tk_window1, t_window1);
}

void ConfirmQuit_window1 ( result)
	int* result; 
{
    static unsigned char _CPS_ConfirmQuit_window1[] = {
 47, 71, 78, 84,110,111,116,105, 99,101,166,144,102,114, 97,109,101, 98,117,102,
102,101,114, 32, 47,110,101,119, 32, 67,108, 97,115,115, 78,111,116,105, 99,101,
 32,115,101,110,100,180,160, 27, 68,111, 32,121,111,117, 32,114,101, 97,108,108,
121, 32,119, 97,110,116, 32,116,111, 32,113,117,105,116, 63, 47,115,101,116,116,
101,120,116, 32, 71, 78, 84,110,111,116,105, 99,101, 32,115,101,110,100, 32, 47,
 71, 78, 84,110,111,116,105, 99,101, 98,117,116,116,111,110,115, 32, 47, 83,112,
 97, 99,101,100, 32,102,114, 97,109,101, 98,117,102,102,101,114, 32, 47,110,101,
119, 32, 67,108, 97,115,115, 66,117,116,116,111,110,115, 32,115,101,110,100,180,
 91,150, 67, 97,110, 99,101,108,156, 67,111,110,102,105,114,109, 32, 81,117,105,
116, 93, 32, 47,115,101,116,105,116,101,109,108,105,115,116, 32, 71, 78, 84,110,
111,116,105, 99,101, 98,117,116,116,111,110,115, 32,115,101,110,100,128,  1, 32,
 47,115,101,116,100,101,102, 97,117,108,116, 32, 71, 78, 84,110,111,116,105, 99,
101, 98,117,116,116,111,110,115, 32,115,101,110,100,128, 10,128,  0, 32, 47,115,
101,116,103, 97,112,115, 32, 71, 78, 84,110,111,116,105, 99,101, 98,117,116,116,
111,110,115, 32,115,101,110,100, 32, 71, 78, 84,110,111,116,105, 99,101, 98,117,
116,116,111,110,115, 32, 47,115,101,116, 98,117,116,116,111,110,115, 32, 71, 78,
 84,110,111,116,105, 99,101, 32,115,101,110,100, 32,119,105,110,100,111,119, 49,
 32, 47,115,101,116, 98, 97,115,101,119,105,110,100,111,119, 32, 71, 78, 84,110,
111,116,105, 99,101, 32,115,101,110,100, 32,123,189,166,209, 47, 99,108,111,115,
101, 32, 71, 78, 84,110,111,116,105, 99,101, 32,115,101,110,100, 32,125, 32, 47,
115,101,116,110,111,116,105,102,105,101,114, 32, 71, 78, 84,110,111,116,105, 99,
101, 98,117,116,116,111,110,115, 32,115,101,110,100, 32,101,109,103,114, 32, 47,
 97, 99,116,105,118, 97,116,101, 32, 71, 78, 84,110,111,116,105, 99,101, 32,115,
101,110,100,128,  0, 32,119,105,110,100,111,119, 49, 32, 47,111,112,101,110, 32,
 71, 78, 84,110,111,116,105, 99,101, 32,115,101,110,100, 32,  0,
};

  pprintf (PostScript, _CPS_ConfirmQuit_window1, 495);
    pscanf (PostScriptInput, "d", result);
}

void setup_ToDoList ()
{
    static unsigned char _CPS_setup_ToDoList[] = "[\234First Object\235Second Object\234Third Object\240\022Fourth thingamajig\2215\2216\2217\2218\2219\22210\22211\22212\240\034The thirteenth and last item] /setitemlist ToDoList send ";

  pprintf (PostScript, _CPS_setup_ToDoList, 139);
}

void cps_add_jot_pane (name,  width,  height,  cv)
	char *name; 
	int width; 
	int height; 
	int cv; 
{
    static unsigned char _CPS_cps_add_jot_pane[] = "%d%d%u%p\246~ADDJ ";

  pprintf (PostScript, _CPS_cps_add_jot_pane, 15, width, height, cv, name);
}

void cps_open_windows ()
{
    static unsigned char _CPS_cps_open_windows[] = "/emgr /new ClassEventMgr send\264emgr /activate window1 send /map window1 send ";

  pprintf (PostScript, _CPS_cps_open_windows, 76);
}
