    /* 
     *  todo_min.cc.new C Interface to Callbacks 
     */


#include <sys/types.h>
#include <strings.h>
#include <stream.h>
#include <libc.h>
#include <NeWS/wire/wire.h>
#include <NeWS/tntguide/alert.h>
#include <NeWS/jot/jot.h>
#include <NeWS/jot/text.h>
#include <NeWS/jot/view.h>
#include <NeWS/jot/undo.h>
#include <NeWS/tntguide/guideJot.h>
#include "todo_min.h"
#include "todo_min_cps.h"

#ifdef PROTO
int	popup_up = FALSE;
#endif /* PROTO */

boolean	gntquit = FALSE;

int t_window1;			/* Tag number for window1 */
int tk_window1;			/* Token number for window1 */


JotText	*textpane1_text;
JotView	*textpane1_view;


int    *tagarray [] =
	{
	&t_window1,
	0
	};

int    *tokenarray [] =
	{
	&tk_window1,
	0
	};



   /*
    * main ()
    *
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	901130	1.0	-Auto-	Stubs Generated by TNTGuide from todo_min.G
    */

int
main (/* int argc, char *argv[] */)
    {
    wire_Wire	 thiswire;
    int	 errno;
    int	 tagnum;
    int	*tagptr[2];
    int	 results = 0;


    tagptr[0] = &tagnum;
    tagptr[1] = NULL;


    if  ((thiswire = wire_Open (NULL)) == wire_INVALID_WIRE)
        {
	errno = wire_Errno;
	printf("\nWire Open Error # %d\n", errno);
        }
    else
        {
	/* Successful connection */
	wire_SetCurrent (thiswire);
	IF_DEBUG( printf("\n Wire opened without error\n"); )
	errno = 0;
        }

    wire_AllocateNamedTags (tagptr);

    if  (runtodo_min ())
        {
	printf("Load File Error \n");
	exit (1);
        }

    while ((!gntquit)  &&  wire_Notify((struct timeval*)NULL))
        {
	if (wire_WouldNotify(thiswire))
	    continue;
	if (JotView_PendingUpdates())
	    JotView_UpdateViews();
	/* Custom code here */
        }

    return 0;
    }   

   /*
    * Allocate_todo_min_Tags ()
    *
    *	Automatically sets up callback routines for each object.
    *	Code is generated by TNTGuide cside
    * 
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	901130	1.0	-Auto-	Stubs Generated by TNTGuide from todo_min.G
    */

void
Allocate_todo_min_Tags()
    {
    wire_Wire	thewire;

    wire_AllocateNamedTags(tagarray);

    /*
     *    Allocate user tokens for the objects
     */

    thewire =wire_Current ();
    wire_AllocateNamedTokens(thewire, tokenarray);

    cps_setwindow1 (t_window1, tk_window1);

    wire_RegisterTag (t_window1,  (wire_Handler)&windowquit,0);
    }


   /*
    * windowquit
    *
    *	Automatically generated callback routine 
    *	for the following object(s):
    *
    *	    window1 (Notifier)
    *
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	901130	1.0	-Auto-	Stubs Generated by TNTGuide from todo_min.G
    */

    void
windowquit (int, caddr_t )
    {
    int result;
    
#ifdef PROTO
    ConfirmQuit_window1 (&result);
    if (result)
        {
        gntquit = 1;
        printf("window1 quit\n");
       }
#else

        /* Custom code goes here */

#endif
    }

   /*
    * runtodo_min
    *	Loads callbacks and the Interface File
    *
    *	Code is generated by TNTGuide cside
    * 
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	901130	1.0	-Auto-	Stubs Generated by TNTGuide from todo_min.G
    */

int
runtodo_min ()
    {
    char	 buf[1024];
    int	 i;

    Jot_Initialize (wire_Current());
    /*
     *	Load your PostScript Files Here
     */

/*  if (i = loadPostScript(yourfile.ps) != 0)
	Process Error Condition */

    /*
     *	Load the server interface file todo_min.ps from the current directory
     */

    if ((i = loadPostScript("todo_min.ps")) != 0)    /* non zero is a error */
	{

#ifdef PROTO
	printf("todo_min.ps did not load\n");

#else
	    /* Custom code for Handling File Load Error */
#endif

	return (i);	/* Error condition from loadPostScript */
	}

    Allocate_todo_min_Tags();
	/*
     * Initialize complex objects
     */

#ifdef PROTO

    /* Initialize textpane1 */
    if  ((textpane1_text = JotText_New(0)) == NULL)
	{
	printf ("textpane1_text: Cannot create text object.\n");
	}
    else 
	JotText_SetUndo (textpane1_text, 32);

    textpane1_view = JotView_New (textpane1_text);
    JotView_SetControllers (textpane1_view, guide_EmacsKeys, NULL, NULL, NULL);

    /*
     * Add the Jot pane and scrollbar
     */
    cps_add_jot_pane ("/textpane1", 323, 295,
		      JotView_Canvas(textpane1_view));

    setup_ToDoList ();
#else	/* PROTO */
	/* Custom code Here */
#endif	/* PROTO */

    /*
     * Activate all windows and open those mapped true
     */
    cps_open_windows();

    return (0);	    /* No error */ 
}   /* runtodo_min */

