/*
 * DO NOT EDIT THIS FILE.  It contains C->PostScript communication
 * definitions that were automatically generated from todo_min_cps.cps
 */
#include <NeWS/c_varieties.h>


EXTERN_FUNCTION (void cps_set_label, (const int win, const char *str));

EXTERN_FUNCTION (void cps_set_footer, (const int win, const char *left, const char *right));

EXTERN_FUNCTION (void cps_label, (const int win, const int tag, char *str));

EXTERN_FUNCTION (void cps_footer, (const int win, const int tag, char *left, char *right));

EXTERN_FUNCTION (void cps_set_named_colors, (const int obj, const char *fg, const char *bg));

EXTERN_FUNCTION (void cps_setwindow1, (const int t_window1, const int tk_window1));

EXTERN_FUNCTION (void ConfirmQuit_window1, (int* result));

EXTERN_FUNCTION (void setup_ToDoList, (_VOID_));

EXTERN_FUNCTION (void cps_add_jot_pane, (const char *name, const int width, const int height, const int cv));

EXTERN_FUNCTION (void cps_open_windows, (_VOID_));


#ifndef PSMACROS_H
#include <NeWS/psmacros.h>		/* standard cdef macros */
#endif
