    /* 
     *  todo_min.cc.new C Interface to Callbacks 
     */


#include <sys/types.h>
#include <strings.h>
#include <stream.h>
#include <libc.h>
#include <NeWS/wire/wire.h>
#include <NeWS/tntguide/alert.h>
#include <NeWS/jot/jot.h>
#include <NeWS/jot/text.h>
#include <NeWS/jot/view.h>
#include <NeWS/jot/undo.h>
#include <NeWS/jot/span.h>
#include <NeWS/tntguide/guideJot.h>
#include "todo_min.h"
#include "todo_min_cps.h"
#include "itementry.h"
#include "todofile.h"


#ifdef PROTO
int	popup_up = FALSE;
#endif /* PROTO */

boolean	gntquit = FALSE;
int numberItems = 0;
ItemEntry * root = NULL;

int t_window1;			/* Tag number for window1 */
int tk_window1;			/* Token number for window1 */
int t_InsertButton;		/* Tag number for InsertButton */
int tk_InsertButton;		/* Token number for InsertButton */
int t_DeleteButton;		/* Tag number for DeleteButton */
int tk_DeleteButton;		/* Token number for DeleteButton */
int t_ToDoList;			/* Tag number for ToDoList */
int tk_ToDoList;		/* Token number for ToDoList */
int tk_HeaderField;


JotText	*textpane1_text;
JotView	*textpane1_view;


int	t_scratch;

int    *tagarray [] =
	{
	&t_window1,
	&t_InsertButton,
	&t_DeleteButton,
	&t_ToDoList,
	&t_scratch,
	0
	};

int    *tokenarray [] =
	{
	&tk_window1,
	&tk_InsertButton,
	&tk_DeleteButton,
	&tk_ToDoList,
	&tk_HeaderField,
	0
	};



   /*
    * main ()
    *
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	910314	1.0	-Auto-	Stubs Generated by gnt from todo_min.G
    */

int
main (/* int argc, char *argv[] */)
    {
    wire_Wire	 thiswire;
    int	 errno;
    int	 tagnum;
    int	*tagptr[2];
    int	 results = 0;


    tagptr[0] = &tagnum;
    tagptr[1] = NULL;


    if  ((thiswire = wire_Open (NULL)) == wire_INVALID_WIRE)
        {
	errno = wire_Errno;
	printf("\nWire Open Error # %d\n", errno);
        }
    else
        {
	/* Successful connection */
	wire_SetCurrent (thiswire);
	IF_DEBUG( printf("\n Wire opened without error\n"); )
	errno = 0;
        }

    wire_AllocateNamedTags (tagptr);

    if  (runtodo_min ())
        {
	printf("Load File Error \n");
	exit (1);
        }

    while ((!gntquit)  &&  wire_Notify((struct timeval*)NULL))
        {
	if (wire_WouldNotify(thiswire))
	    continue;
	if (JotView_PendingUpdates())
	    JotView_UpdateViews();
	/* Custom code here */
        }
	wire_Close(thiswire);
    return 0;
    }   

   /*
    * Allocate_todo_min_Tags ()
    *
    *	Automatically sets up callback routines for each object.
    *	Code is generated by gnt cside
    * 
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	910314	1.0	-Auto-	Stubs Generated by gnt from todo_min.G
    */

void
Allocate_todo_min_Tags()
    {
    wire_Wire	thewire;

    wire_AllocateNamedTags(tagarray);

    /*
     *    Allocate user tokens for the objects
     */

    thewire =wire_Current ();
    wire_AllocateNamedTokens(thewire, tokenarray);

    cps_setwindow1 (t_window1, tk_window1);
    cps_setInsertButton (t_InsertButton, tk_InsertButton);
    cps_setDeleteButton (t_DeleteButton, tk_DeleteButton);
    cps_setToDoList (t_ToDoList, tk_ToDoList);
    PS_SetHeaderFieldToken(tk_HeaderField);

    wire_RegisterTag (t_window1,  (wire_Handler)&windowquit,0);
    wire_RegisterTag (t_InsertButton,  (wire_Handler)&InsertItemHandler,0);
    wire_RegisterTag (t_DeleteButton,  (wire_Handler)&DeleteItemHandler,0);
    wire_RegisterTag (t_ToDoList,  (wire_Handler)&ChooseItemHandler,0);
    }

   /*
    * runtodo_min
    *	Loads callbacks and the Interface File
    *
    *	Code is generated by gnt cside
    * 
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	910314	1.0	-Auto-	Stubs Generated by gnt from todo_min.G
    */

int
runtodo_min ()
    {
    int	 i;

    Jot_Initialize (wire_Current());
    /*
     *	Load your PostScript Files Here
     */

/*  if (i = loadPostScript(yourfile.ps) != 0)
	Process Error Condition */

    /*
     *	Load the server interface file todo_min.ps from the current directory
     */

    if ((i = loadPostScript("todo_min.ps")) != 0)    /* non zero is a error */
	{

#ifdef PROTO
	printf("todo_min.ps did not load\n");

#else
	    /* Custom code for Handling File Load Error */
#endif

	return (i);	/* Error condition from loadPostScript */
	}

    Allocate_todo_min_Tags();
	/*
     * Initialize complex objects
     */


    /* Initialize textpane1 */
    if  ((textpane1_text = JotText_New(0)) == NULL)
	{
#ifdef PROTO
	printf ("textpane1_text: Cannot create text object.\n");
#else
 	/* Custom Code Here */
#endif
	}
    else 
	JotText_SetUndo (textpane1_text, 32);

    textpane1_view = JotView_New (textpane1_text);
    JotView_SetControllers (textpane1_view, guide_EmacsKeys, NULL, NULL, NULL);

    /*
     * Add the Jot pane and scrollbar
     */
    cps_add_jot_pane ("/textpane1", 323, 295,
		      JotView_Canvas(textpane1_view));

    setup_ToDoList ();
    /*
     * Activate all windows and open those mapped true
     */
    cps_open_windows();

    return (0);	    /* No error */ 
}   /* runtodo_min */


   /*
    * windowquit
    *
    *	Automatically generated callback routine 
    *	for the following object(s):
    *
    *	    window1 (Notifier)
    *
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	910314	1.0	-Auto-	Stubs Generated by gnt from todo_min.G
    */

    void
windowquit (int, caddr_t )
    {
    int result;
    cps_ConfirmQuit_window1 (&result,t_scratch);
    if (result)
        {
        gntquit = 1;
#ifdef PROTO
        printf("Client callback invoked: window1 quit\n");
#else
    /* Custom Code Here */
#endif
       }
    }


   /*
    * InsertItemHandler
    *
    *	Automatically generated callback routine 
    *	for the following object(s):
    *
    *	    InsertButton (Notifier)
    *
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	910314	1.0	-Auto-	Stubs Generated by gnt from todo_min.G
    */

    void
InsertItemHandler (int, caddr_t )
    {

#ifdef PROTO
    printf("Client callback invoked: InsertButton called  \n");
#else

        /* Custom code goes here */
      char itemHeader[HDRSIZE];
      char buf[ENTRYSIZE];
      int howMany;
      JotSpan *span;
      ItemEntry * newItem;

      buf[0] = '\0';
      itemHeader[0] = ':';  // Used as key in item file
      PS_GetHeader(tk_HeaderField, &itemHeader[1], t_scratch);
      numberItems++;

      // If no header, put in the current index
      if (itemHeader[1] == '\0') {
	sprintf(&itemHeader[1], "%d", numberItems);
	PS_SetHeader(tk_HeaderField, &itemHeader[1]);
      }

      // Get the text from Jot
      howMany = JotText_Characters(textpane1_text);
      span = JotSpan_New(textpane1_text, 0, howMany);
      if ((howMany = JotSpan_Contents(span, buf)) == -1) {
	buf[0] = '\0';
      } else {
	buf[howMany] = '\0';
      }

      // Initialize a new ItemEntry
      newItem = new ItemEntry(itemHeader, buf, NULL);
      newItem->SetIndex(numberItems-1);
      
      // Append the new item
      AppendItem(root, newItem);
      
      // Update the scrolling list
      PS_AppendItemToList(tk_ToDoList, &itemHeader[1]);
      PS_SetDefaultItem(tk_ToDoList, numberItems-1);
      JotSpan_Free(span);

#endif
    }


   /*
    * DeleteItemHandler
    *
    *	Automatically generated callback routine 
    *	for the following object(s):
    *
    *	    DeleteButton (Notifier)
    *
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	910314	1.0	-Auto-	Stubs Generated by gnt from todo_min.G
    */

    void
DeleteItemHandler (int, caddr_t )
    {

#ifdef PROTO
    printf("Client callback invoked: DeleteButton called  \n");
#else

        /* Custom code goes here */
      int whichItem;
      int newDefaultIndex;
      ItemEntry * newDefault;
      PS_GetListValue(tk_ToDoList, &whichItem, t_scratch);
      if (whichItem == -1) return;

      numberItems--;
      DeleteItem(root, whichItem);
      PS_DeleteItemFromList(tk_ToDoList, whichItem);
      
      // Find the new item to display
      newDefaultIndex = NewDefaultItem(whichItem, numberItems);
      JotText_Clear(textpane1_text);
      if (newDefaultIndex >= 0) {
	PS_SetDefaultItem(tk_ToDoList, newDefaultIndex);
	newDefault = FindItem(root, newDefaultIndex);
	JotText_InsertString(textpane1_text, 0, newDefault->GetItem());
	PS_SetHeader(tk_HeaderField,newDefault->GetHeader());
      } else {
	PS_ClearHeader(tk_HeaderField);	
	}
#endif
    }


   /*
    * ChooseItemHandler
    *
    *	Automatically generated callback routine 
    *	for the following object(s):
    *
    *	    ToDoList (Notifier)
    *
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	910314	1.0	-Auto-	Stubs Generated by gnt from todo_min.G
    */

    void
ChooseItemHandler (int, caddr_t )
    {
    int index;		/* Index of selected item */
    int state;		/* Boolean of selected */
    char buf[256];	/* Buffer for string */
    index = wire_ReadInt ();
    state = wire_ReadInt ();
    wire_ReadString (buf);


#ifdef PROTO
    if (state)
        printf("Client callback invoked: ToDoList called with index %d value %s true\n", index, buf);
    else
        printf("Client callback invoked: ToDoList called with index %d value %s false\n", index, buf);
#else

        /* Custom code goes here */
    if (state) {       // An item was turned on in the list
      ItemEntry * which = FindItem(root, index);
      if (!which) return;

      JotText_Clear(textpane1_text);
      JotText_InsertString(textpane1_text, 0, which->GetItem());
//      JotView_Update(textpane1_view);
      PS_SetHeader(tk_HeaderField, which->GetHeader());
    }
    // If the item was turned off, we ignore it.

#endif
    }

