/* DO NOT EDIT THIS FILE.  It contains C->PostScript communication
   definitions that were automatically generated from color_cps.cps */

#define ps_createhsbcolor(P__0,P__1,P__2,P__3)  pprintf(PostScript, _CPS_ps_createhsbcolor, 12, P__0, P__1, P__2, P__3)
extern char _CPS_ps_createhsbcolor[];
#define ps_usecolor(P__0)  pprintf(PostScript, _CPS_ps_usecolor, 3, P__0)
extern char _CPS_ps_usecolor[];
#ifndef PSMACROS_H
#include <NeWS/psmacros.h>		/* standard cdef macros */
#endif
