/*
 * DO NOT EDIT THIS FILE.  It contains C->PostScript communication
 * definitions that were automatically generated from alertcps.cps
 */
static unsigned char _CPS_RunPopUp[] = "%s\246<\246M/place\200\001\246psend /map\200\001\246psend /totop\266send ";
#define RunPopUp(P__0)	\
pprintf (PostScript, _CPS_RunPopUp, 46, P__0)



#ifndef PSMACROS_H
#include <NeWS/psmacros.h>		/* standard cdef macros */
#endif
