/*
 * DO NOT EDIT THIS FILE.  It contains C->PostScript communication
 * definitions that were automatically generated from chooser_cps.cps
 */
#include <NeWS/c_varieties.h>


EXTERN_FUNCTION (void PS_Paint, (const int cv));

EXTERN_FUNCTION (void PS_SetSliderVariable, (const int cv, const char *slidername, const float val));

EXTERN_FUNCTION (void PS_RegisterTag, (const int obj, const char *tagname, const int tagvalue));

EXTERN_FUNCTION (void PS_AssociateTokens, (const int tk1, const int tk2));

EXTERN_FUNCTION (void PS_LoadClasses, (const int tk1, const int tk2));


#ifndef PSMACROS_H
#include <NeWS/psmacros.h>		/* standard cdef macros */
#endif
