;GIL-2
(
(
	:type                   :popup-window
	:name                   popup1
	:owner                  nil
	:width                  200
	:height                 128
	:background-color       ""
	:foreground-color       ""
	:label                  "Popup Window"
	:label-type             :string
	:mapped                 t
	:show-footer            t
	:resizable              t
	:pinned                 nil
	:done-handler           nil
	:event-handler          nil
	:events                 ()
	:user-data              ()
)
(
	:type                   :popup-window
	:name                   popup2
	:owner                  nil
	:width                  250
	:height                 150
	:background-color       "Cadet Blue"
	:foreground-color       ""
	:label                  "number 2"
	:label-type             :string
	:mapped                 t
	:show-footer            nil
	:resizable              nil
	:pinned                 t
	:done-handler           nil
	:event-handler          nil
	:events                 ()
	:user-data              ()
)
)
