;GIL-2
(
(
	:type                   :base-window
	:name                   window1
	:owner                  nil
	:width                  400
	:height                 150
	:background-color       "Cadet Blue"
	:foreground-color       ""
	:label                  "Base Window"
	:label-type             :string
	:mapped                 t
	:show-footer            t
	:resizable              t
	:icon-file              ""
	:icon-mask-file         ""
	:event-handler          nil
	:events                 ()
	:user-data              ()
)
(
	:type                   :canvas-pane
	:name                   canvas1
	:owner                  window1
	:help                   ""
	:x                      0
	:y                      0
	:width                  64
	:height                 64
	:background-color       "BG1"
	:foreground-color       ""
	:menu                   nil
	:horizontal-scrollbar   nil
	:scrollable-width       64
	:vertical-scrollbar     nil
	:scrollable-height      64
	:repaint-proc           nil
	:event-handler          nil
	:events                 ()
	:drawing-model          :xview
	:user-data              ()
)
(
	:type                   :canvas-pane
	:name                   canvas2
	:owner                  window1
	:help                   ""
	:x                      64
	:y                      0
	:width                  64
	:height                 64
	:background-color       "BG2"
	:foreground-color       ""
	:menu                   nil
	:horizontal-scrollbar   nil
	:scrollable-width       64
	:vertical-scrollbar     nil
	:scrollable-height      64
	:repaint-proc           nil
	:event-handler          nil
	:events                 ()
	:drawing-model          :xview
	:user-data              ()
)
(
	:type                   :canvas-pane
	:name                   canvas3
	:owner                  window1
	:help                   ""
	:x                      128
	:y                      0
	:width                  64
	:height                 64
	:background-color       "BG3"
	:foreground-color       ""
	:menu                   nil
	:horizontal-scrollbar   nil
	:scrollable-width       64
	:vertical-scrollbar     nil
	:scrollable-height      64
	:repaint-proc           nil
	:event-handler          nil
	:events                 ()
	:drawing-model          :xview
	:user-data              ()
)
(
	:type                   :canvas-pane
	:name                   canvas4
	:owner                  window1
	:help                   ""
	:x                      192
	:y                      0
	:width                  64
	:height                 64
	:background-color       "Highlight"
	:foreground-color       ""
	:menu                   nil
	:horizontal-scrollbar   nil
	:scrollable-width       64
	:vertical-scrollbar     nil
	:scrollable-height      64
	:repaint-proc           nil
	:event-handler          nil
	:events                 ()
	:drawing-model          :xview
	:user-data              ()
)
(
	:type                   :canvas-pane
	:name                   canvas5
	:owner                  window1
	:help                   ""
	:x                      256
	:y                      0
	:width                  64
	:height                 64
	:background-color       "Aquamarine"
	:foreground-color       ""
	:menu                   nil
	:horizontal-scrollbar   nil
	:scrollable-width       64
	:vertical-scrollbar     nil
	:scrollable-height      64
	:repaint-proc           nil
	:event-handler          nil
	:events                 ()
	:drawing-model          :xview
	:user-data              ()
)
(
	:type                   :canvas-pane
	:name                   canvas6
	:owner                  window1
	:help                   ""
	:x                      320
	:y                      0
	:width                  80
	:height                 64
	:background-color       "Black"
	:foreground-color       ""
	:menu                   nil
	:horizontal-scrollbar   nil
	:scrollable-width       80
	:vertical-scrollbar     nil
	:scrollable-height      64
	:repaint-proc           nil
	:event-handler          nil
	:events                 ()
	:drawing-model          :xview
	:user-data              ()
)
)
