/*
 * @(#)synch.c 1.10 91/02/21 Copyright 1990-91 Sun Microsystems
 *
 * This file is a product of Sun Microsystems, Inc. and is provided for
 * unrestricted use provided that this legend is included on all tape
 * media and as a part of the software program in whole or part.  Users
 * may copy or modify this file without charge, but are not authorized to
 * license or distribute it to anyone else except as part of a product
 * or program developed by the user.
 * 
 * THIS FILE IS PROVIDED AS IS WITH NO WARRANTIES OF ANY KIND INCLUDING THE
 * WARRANTIES OF DESIGN, MERCHANTIBILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE OR TRADE PRACTICE.
 * 
 * This file is provided with no support and without any obligation on the
 * part of Sun Microsystems, Inc. to assist in its use, correction,
 * modification or enhancement.
 * 
 * SUN MICROSYSTEMS, INC. SHALL HAVE NO LIABILITY WITH RESPECT TO THE
 * INFRINGEMENT OF COPYRIGHTS, TRADE SECRETS OR ANY PATENTS BY THIS FILE
 * OR ANY PART THEREOF.
 * 
 * In no event will Sun Microsystems, Inc. be liable for any lost revenue
 * or profits or other special, indirect and consequential damages, even
 * if Sun has been advised of the possibility of such damages.
 * 
 * Sun Microsystems, Inc.
 * 2550 Garcia Avenue
 * Mountain View, California  94043
 */

/*****************************************************************************
This package implements the C side of the PS-to-C synchronisation code.  Most
of the dirty work is done on the PS side, but this seems like a better place
to document how the synchronisation works.

The general interface is in PS, where a client calls wire_Sync and gives it a
procedure on the stack.  wire_Sync calls the procedure and then sends a
marker to the C client, and waits for the client to acknowledge having seen
the marker before the PS process is allowed to proceed.  Thus, for example,
PS can ask C to send it some value, or to do some painting, etc., and be sure
that C has responded to the request before trying to do any more PS code.

In the simple case, the PS is running in a process separate from the one that
reads the client connection.  Then the PS process is simply suspended until C
sends an acknowledgement that wakes up that process.  The acknowledgement
implies that C has seen and responded to any PS requests sent prior to the
suspension.

In the more difficult case, the PS is running in the same process as the
"listener".  E.g., the client sends a request to PS, and in the course of
processing that request the PS side concludes it needs some information or
other assistance from the client.  This case is complicated for two reasons.
First, the PS process cannot simply suspend, because then there will be no
process left to read the wire, so the wake-up message will never get read.
Second, there may be additional stuff already in transit on the wire, which
we do NOT want to execute until after processing the current request.  E.g.,
if the client tells PS to do P then Q, and operation P decides it wants to
ask for something from the client, the client will respond by sending P2.
The sequence of text on the wire is P Q P2, but we in fact want to execute P
P2 Q.  Indeed, even that is not quite true, because we want to execute P2 in
the MIDDLE of P, to wit at whatever point P called wire_Sync.  Things get
even more obscure if the client response to a sync message itself makes a
synchronised request.  Again, this magic is implemented primarily on the PS
side.

Here's the "canonical scenario" used to test the "listener
process" case.

Summary:

> Client wants to send {A} {B} {C} {D} {E} {F}.

> In the course of executing {B}, PS wants to do {B1 B2 B3 B4 B5}, where
  B2 and B4 are requests for additional commands from the client.

> The commands from C to do B2 are {B2X B2Y B2Z}; for B4 it's {B4X}.

> B2Y in turn is a function that looks like {B2Ya B2Yb B2Yc}, where
  B2Yb is yet another request for stuff from the client.

> The client response to B2Yb is {Q}.

Sequence:

> The client will get as far as sending {C} before seeing the PS request for
  B2.  It will respond to that, then ship {D}, then see the request for B2Yb
  (generated by PS as a result of the response to B2).  It responds to that,
  then ships {E}, then sees and responds to the request for B4.  And finally
  it ships {F}.

> The sequence of stuff down the wire to the server is therefore:
	{A} {B} {C} {B2X B2Y B2Z} {D} {Q} {E} {B4X} {F}
  Representing start/end markers with < >, and "final" with *, this becomes:
	{A} {B} {C} < {B2X B2Y B2Z} >* {D} < {Q} >* {E} < {B4X} >* {F}

> The sequence in which this is supposed to be executed on the server is:
	A
	B => (PS function call)
	    B1
	    B2 => (request for code from client)
	    	B2X
	    	B2Y => (PS function call)
	    	    B2Ya
	    	    B2Yb => (request for code from client)
	    	    	Q
	    	    B2Yc
	    	B2Z
	    B3
	    B4 =>
	    	B4X
	    B5
	C
	D
	E
	F

Detailed scenario:

> The client sends {A} {B} {C}.

> The listener process reads and executes {A} and {B}.  The latter is a
  function that executes B1, then calls sync to execute B2.
  
> Sync sends a startsync request over the wire, then executes B2 which
  sends the specific request to the client, then sends an endsync request.

> The client loop sees the startsync request and sends an ACK (the "<" in
  the summary of wire traffic).  Then it sees the B2 request and responds by
  shipping {B2X B2Y B2Z}.  Then it sees the endsync request and sends >*.

> The client then goes on its merry way and decides to ship {D}.

> Meanwhile, the sync code has taken over the listener and is reading stdin
  looking for the startsync ACK (<).  The intervening stuff (C) is saved to
  be executed at level 0.  Then B2X is read and executed, and B2Y is read
  and executed.
  
> B2Y is a function that performs B2Ya, then calls sync to execute B2Yb.

> Sync sends a startsync req, executes B2Yb, and sends an endsync req.  Then
  it takes over listening to the wire.  The callstack now looks like:
  	listener
  	B (still waiting to execute B3 B4 B5)
  	B2
  	sync (level 1)
  	B2Y (still waiting to execute B2Yc)
  	B2Yb
  	sync (level 2, reading the wire)
  The wire has been read as far as B2Y.

> The client, having already shipped {D}, sees this new request and sends
  < {Q} >*.

> The level-2 sync reads the wire looking for the startsync ACK.  Before it
  finds one, it comes to an endsync (>).  It saves the intervening stuff (B2Z)
  to be executed at level 1.  It discards the *, appends {D} to the stuff to
  be executed at level 0, and reaches the ACK.

> The level-2 sync then reads and executes {Q}, then reads and executes an
  endsynch token, which sets a flag that causes ALL levels of sync to end.
  (It is guaranteed that, if the nested sync is exiting, the endsynch tokens
  for all higher levels of sync were already encountered earlier.)

> The level-2 sync exits its loop, checks for stuff cached for execution at
  level 2 (there isn't any), and returns.

> That finishes B2Yb, so B2Y proceeds with B2Yc, then returns.

> Going up the callstack, we're back at the level-1 sync.  Since the sync
  exit flag is still set, it stops reading the wire.  It checks for stuff
  saved to be executed at level 1 and executes it: B2Z.  Then it returns.

> That finishes B2, so B proceeds with B3 and B4.  B4 invokes sync a third
  time, this time at level 1 again.  Requests are shipped to the client.

> The client, meanwhile, has already shipped {E}.  Now it sees the new
  request and sends < {B4X} >*.

> The sync code takes over reading the wire, looking for the ACK.  The first
  thing it finds is the * left over after {Q}.  (The previous sync exited
  when it read the endsynch (>), but deliberately left the * on the stream.)
  The sync code discards the *.  It finds {E} and appends it to the stuff to
  be executed at level 0.
  
> Then it comes to the <, and reads and executes B4X.  Next comes a >, which
  sets the exit flag, so sync stops reading the wire.  It looks for stuff to
  be executed at level 1 and finds none.  (The previous execution of B2Z also
  removed it from the cache.)  It returns.

> That finishes B4, so B proceeds with B5, then returns.

> Now the listener process itself is back in control.  It reads the next
  token on the wire, which is the * left over after B4X.  This time the *
  token actually gets executed, and it has the effect of performing the stuff
  cached for execution at level 0, to wit: {C} {D} {E}.

> The client sends {F}, and the listener reads it and executes it.
  Everything is back to normal.

NOTES:

> This probably doesn't work if wire_Sync is invoked in a nested file.  That
  is, if the client sends "(/foo/bar/bletch.ps) run" down the wire, and
  bletch.ps tries to call wire_Sync, wire_Sync will finish reading the file
  bletch, but then it has no way of getting at the connection file without
  popping itself (wire_Sync) off the execution stack.  And since the response
  to the sync will presumably be in the connection file, you're hosed.

> You're also be hosed if you call wire_Sync from a non-listener process, and
  the response from the client requires some process-specific context.  This
  might be fixable with some effort, but it would slow down all the cases
  where the client response is happy to execute in the listener context.

*****************************************************************************/

#include <stdio.h>
#include "synch_cps.h"

#include "wire.h"
#include "wire_private.h"

static int synctag = -1;
static int expectedsynctag;

/* Handle a synch-request tag.  The accompanying int is:
 *	 0 for a Start
 *	-1 for an End
 *	-2 to turn on BindOverride in the listener PS process
 *	-3 to restore the previous state of BindOverride, and
 *	>0 for a Wake (non-listener process).
 */
static void
SyncStuff(tag)
{
	int id;

	ps_getsyncID(&id);
	switch (id) {
		case 0:
			wire_ConnectionTable[wire_Current()]->sync_level++;
			ps_startsync();
			break;
		case -1:
			wire_ConnectionTable[wire_Current()]->sync_level--;
			ps_endsync();
			break;
		case -2:
			ps_bindoverride();
			break;
		case -3:
			ps_bindrestore();
			break;
		default:
			ps_wakesync(id);
			break;
	}
	ps_flush_PostScript();
}

static void
ExpectedSyncDone(tag)
{
	int		w;
	wire_Wire	wire;

	w = wire_ReadInt();
	wire = wire_IntToWire(w);
	assert(wire_ConnectionTable[wire]->expected_syncs > 0);
	wire_ConnectionTable[wire]->expected_syncs -= 1;
}

boolean
wire_ExpectSync(wire)
wire_Wire   wire;
{
	if (!wire_Valid(wire))
		return FALSE;
	wire_ConnectionTable[wire]->expected_syncs += 1;
	ps_expectedsyncdone(wire_WireToInt(wire), expectedsynctag);
	ps_flush_PostScript();
	return TRUE;
}

boolean
wire_DrainSync(wire, notify_proc)
wire_Wire	wire;
void		(*notify_proc)();
{
	if (!wire_Valid(wire))
		return FALSE;
	while (wire_ConnectionTable[wire]->expected_syncs > 0)
		if (notify_proc == NULL)
			wire_Notify(NULL);
		else
			(*notify_proc)();
	return TRUE;
}

/* Send initialisation PS down the current wire.  Allocates synctag if this
 * is the first connection.
 */
void wire_SyncInit(wire)
wire_Wire	wire;
{
	if (synctag < 0) {
		synctag = wire_AllocateTags(2);
		expectedsynctag = synctag + 1;
		wire_RegisterTag(synctag, SyncStuff, NULL);
		wire_RegisterTag(expectedsynctag, ExpectedSyncDone, NULL);
	}
	ps_initsync(synctag);
	wire_ConnectionTable[wire]->sync_level = 0;
}

boolean
wire_InSync(wire)
wire_Wire	wire;
{
	return (wire_ConnectionTable[wire]->sync_level != 0);
}
