    /* 
     *  chooser.c.new C Interface to Callbacks 
     */


#include <sys/types.h>
#include <strings.h>
#include <stdio.h>
#include <NeWS/wire/wire.h>
#include <NeWS/tntguide/alert.h>
#include "chooser.h"
#include "chooser_cps.h"

#ifdef PROTO
int	popup_up = FALSE;
#endif /* PROTO */

boolean	gntquit = FALSE;

int t_window1;			/* Tag number for window1 */
int tk_window1;			/* Token number for window1 */


int	t_scratch;

int    *tagarray [] =
	{
	&t_window1,
	&t_scratch,
	0
	};

int    *tokenarray [] =
	{
	&tk_window1,
	0
	};



   /*
    * main ()
    *
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	910314	1.0	-Auto-	Stubs Generated by gnt from chooser.G
    */

int
main (argc, argv)
    int argc;
    char *argv[];
    {
    wire_Wire	 thiswire;
    int	 errno;
    int	 tagnum;
    int	*tagptr[2];
    int	 results = 0;


    tagptr[0] = &tagnum;
    tagptr[1] = NULL;


    if  ((thiswire = wire_Open (NULL)) == wire_INVALID_WIRE)
        {
	errno = wire_Errno;
	printf("\nWire Open Error # %d\n", errno);
        }
    else
        {
	/* Successful connection */
	wire_SetCurrent (thiswire);
	IF_DEBUG( printf("\n Wire opened without error\n"); )
	errno = 0;
        }

    wire_AllocateNamedTags (tagptr);

    if  (runchooser ())
        {
	printf("Load File Error \n");
	exit (1);
        }

    while ((!gntquit)  &&  wire_Notify((struct timeval*)NULL))
        {
	if (wire_WouldNotify(thiswire))
	    continue;
	/* Custom code here */
        }

    return 0;
    }   

   /*
    * Allocate_chooser_Tags ()
    *
    *	Automatically sets up callback routines for each object.
    *	Code is generated by gnt cside
    * 
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	910314	1.0	-Auto-	Stubs Generated by gnt from chooser.G
    */

void
Allocate_chooser_Tags()
    {
    wire_Wire	thewire;

    wire_AllocateNamedTags(tagarray);

    /*
     *    Allocate user tokens for the objects
     */

    thewire =wire_Current ();
    wire_AllocateNamedTokens(thewire, tokenarray);

    cps_setwindow1 (t_window1, tk_window1);

    wire_RegisterTag (t_window1, windowquit,0);
    }

   /*
    * runchooser
    *	Loads callbacks and the Interface File
    *
    *	Code is generated by gnt cside
    * 
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	910314	1.0	-Auto-	Stubs Generated by gnt from chooser.G
    */

int
runchooser ()
    {
    int	 i;

    /*
     *	Load your PostScript Files Here
     */

/*  if (i = loadPostScript(yourfile.ps) != 0)
	Process Error Condition */

    /*
     *	Load the server interface file chooser.ps from the current directory
     */

    if ((i = loadPostScript("chooser.ps")) != 0)    /* non zero is a error */
	{

#ifdef PROTO
	printf("chooser.ps did not load\n");

#else
	    /* Custom code for Handling File Load Error */
#endif

	return (i);	/* Error condition from loadPostScript */
	}

    Allocate_chooser_Tags();
    /*
     * Activate all windows and open those mapped true
     */
    cps_open_windows();

    return (0);	    /* No error */ 
}   /* runchooser */


   /*
    * windowquit
    *
    *	Automatically generated callback routine 
    *	for the following object(s):
    *
    *	    window1 (Notifier)
    *
    * Revision History:
    *
    *	Date	Vers	Who	What
    *	===============================================================
    *	910314	1.0	-Auto-	Stubs Generated by gnt from chooser.G
    */

    void
windowquit (tag, data)
    int tag;
    caddr_t data;
    {
    int result;
    cps_ConfirmQuit_window1 (&result,t_scratch);
    if (result)
        {
        gntquit = 1;
#ifdef PROTO
        printf("Client callback invoked: window1 quit\n");
#else
    /* Custom Code Here */
#endif
       }
    }

