    %/*
    % *    chooser.cps generated by gnt
    % */

cdef	cps_set_label(token win, string str)
	%/*
	% *	Set the label string for the given window
	% */
	str /setlabel win send

cdef	cps_set_footer(token win, string left, string right)
	%/*
	% *	Set the footer strings in the given window
	% */
	left right /setfooter win send

cdef	cps_label(token win, int tag, string str)	=> tag (str)
	%/*
	% *	Return the current label string from the given window
	% */
	/label win send
	tag tagprint
	dup null eq { pop () } if typedprint

cdef	cps_footer(token win, int tag, string left, string right)
	=> tag (right, left)
	%/*
	% *	Return the current footer strings from the given window
	% */
	/footer win send
	tag tagprint
	dup null eq { pop () } if typedprint
	dup null eq { pop () } if typedprint


cdef	cps_set_named_colors(token obj, postscript fg, postscript bg)
	%/*
	% *	Set the foreground and background colors for the object.
	% *	If either parameter is null, use the current color.
	% */
	/colors obj send
	bg dup null ne { ColorDict exch get exch } if pop exch
	fg dup null ne { ColorDict exch get exch } if pop exch
	/setcolors obj send


cdef	cps_setwindow1 (t_window1, tk_window1)
	window1 tk_window1 setfileinputtoken
	/tagnum t_window1 /setproperty window1 send

cdef	cps_ConfirmQuit_window1 (result, int tag) => tag (result)
	/GNTnotice null framebuffer /new ClassNotice send def
	(Do you really want to quit?) /settext GNTnotice send
	/GNTnoticebuttons /Spaced framebuffer /new ClassButtons send def
	[(Cancel) (Confirm Quit)] /setitemlist GNTnoticebuttons send
	1 /setdefault GNTnoticebuttons send
	10 0 /setgaps GNTnoticebuttons send
	GNTnoticebuttons /setbuttons GNTnotice send
	window1 /setbasewindow GNTnotice send
	{tag tagprint pop typedprint /close GNTnotice send} /setnotifier GNTnoticebuttons send
	emgr /activate GNTnotice send
	0 window1 /open GNTnotice send

cdef	cps_open_windows()
	%
	% Activate all windows and open those mapped true
	%
	/emgr /new ClassEventMgr send def
	emgr /activate window1 send
	/map window1 send

