/* DO NOT EDIT THIS FILE.  It contains C->PostScript communication
   definitions that were automatically generated from psmacros.cps */

/*
 * @(#)psmacros.h 1.5 91/02/21 Copyright 1990-91 Sun Microsystems
 *
 * This file is a product of Sun Microsystems, Inc. and is provided for
 * unrestricted use provided that this legend is included on all tape
 * media and as a part of the software program in whole or part.  Users
 * may copy or modify this file without charge, but are not authorized to
 * license or distribute it to anyone else except as part of a product
 * or program developed by the user.
 * 
 * THIS FILE IS PROVIDED AS IS WITH NO WARRANTIES OF ANY KIND INCLUDING THE
 * WARRANTIES OF DESIGN, MERCHANTIBILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE OR TRADE PRACTICE.
 * 
 * This file is provided with no support and without any obligation on the
 * part of Sun Microsystems, Inc. to assist in its use, correction,
 * modification or enhancement.
 * 
 * SUN MICROSYSTEMS, INC. SHALL HAVE NO LIABILITY WITH RESPECT TO THE
 * INFRINGEMENT OF COPYRIGHTS, TRADE SECRETS OR ANY PATENTS BY THIS FILE
 * OR ANY PART THEREOF.
 * 
 * In no event will Sun Microsystems, Inc. be liable for any lost revenue
 * or profits or other special, indirect and consequential damages, even
 * if Sun has been advised of the possibility of such damages.
 * 
 * Sun Microsystems, Inc.
 * 2550 Garcia Avenue
 * Mountain View, California  94043
 */

/*
 * This is a direct copy of the OpenWindows 2.0 preFCS psmacros.h, with the
 * two external function declarations converted to use the EXTERN_FUNCTION()
 * macro from the c_varieties header.
 */

#ifndef PSMACROS_H
#define PSMACROS_H
#ifndef FILE
#include <stdio.h>
#include <NeWS/c_varieties.h>
#endif
#ifndef PSFILE
#include <NeWS/psio.h>
#endif
extern PSFILE *PostScript, *PostScriptInput;
EXTERN_FUNCTION( PSFILE *ps_open_PostScript,	(_VOID_) );
EXTERN_FUNCTION( PSFILE *ps_open_server,	(char *server) );
#define ps_flush_PostScript() (psio_setblockok(PostScript), \
psio_flush(PostScript))
#define ps_close_server(p)	 (psio_close(psio_getassoc(p)), psio_close(p))
#define ps_close_PostScript() (psio_close(PostScript),PostScript = 0, \
psio_close(PostScriptInput),PostScriptInput=0)
#define ps_moveto(P__0,P__1)  pprintf(PostScript, _CPS_ps_moveto, 5, P__0, P__1)
extern unsigned char _CPS_ps_moveto[];
#define ps_rmoveto(P__0,P__1)  pprintf(PostScript, _CPS_ps_rmoveto, 5, P__0, P__1)
extern unsigned char _CPS_ps_rmoveto[];
#define ps_lineto(P__0,P__1)  pprintf(PostScript, _CPS_ps_lineto, 5, P__0, P__1)
extern unsigned char _CPS_ps_lineto[];
#define ps_rlineto(P__0,P__1)  pprintf(PostScript, _CPS_ps_rlineto, 5, P__0, P__1)
extern unsigned char _CPS_ps_rlineto[];
#define ps_closepath() psio_putc('\263', PostScript)
#define ps_arc(P__0,P__1,P__2,P__3,P__4)  pprintf(PostScript, _CPS_ps_arc, 11, P__0, P__1, P__2, P__3, P__4)
extern unsigned char _CPS_ps_arc[];
#define ps_stroke() psio_putc('\305', PostScript)
#define ps_fill() psio_putc('\267', PostScript)
#define ps_show(P__0)  pprintf(PostScript, _CPS_ps_show, 3, P__0)
extern unsigned char _CPS_ps_show[];
#define ps_cshow(P__0,L__0)  pprintf(PostScript, _CPS_ps_cshow, 4, L__0, P__0)
extern unsigned char _CPS_ps_cshow[];
#define ps_findfont(P__0)  pprintf(PostScript, _CPS_ps_findfont, 3, P__0)
extern unsigned char _CPS_ps_findfont[];
#define ps_scalefont(P__0)  pprintf(PostScript, _CPS_ps_scalefont, 3, P__0)
extern unsigned char _CPS_ps_scalefont[];
#define ps_setfont() psio_putc('\302', PostScript)
#define ps_gsave() psio_putc('\272', PostScript)
#define ps_grestore() psio_putc('\271', PostScript)
#define ps_check_PostScript_event()				\
(psio_availinputbytes(PostScriptInput) ||		\
ps_checkfor(PostScriptInput,PSIO_CHECK_INPUT,0))
#define ps_check_input()		ps_check_PostScript_event()
#define ps_query_PostScript_event(tag)	\
ps_checkfor(PostScriptInput,PSIO_FIND_TAG,tag)
#define ps_query_tag(tag)		ps_query_PostScript_event(tag)
#define ps_read_PostScript_event(ptag)	\
ps_currenttag(PostScriptInput,PSIO_GET_TAG,ptag)
#define ps_read_tag(ptag)		ps_read_PostScript_event(ptag)
#define ps_peek_PostScript_event(ptag)	\
ps_currenttag(PostScriptInput,PSIO_PEEK_TAG,ptag)
#define ps_peek_tag(ptag)		ps_peek_PostScript_event(ptag)
#define ps_skip_PostScript_event()	\
ps_skip(PostScriptInput)
#define ps_skip_input_value()	ps_skip_PostScript_event()
#define ps_define_stack_token(u) ps_DO_defuser(u/**/_token = psio_getnexttoken(PostScript))
#define ps_define_value_token(u) (pprintf(PostScript, "/u load ", sizeof "/u load " - 1), \
ps_define_stack_token(u))
#define ps_define_word_token(u) (pprintf(PostScript, "/u cvx ", sizeof "/u cvx " - 1), \
ps_define_stack_token(u))
#define ps_DO_defuser(P__0)  pprintf(PostScript, _CPS_ps_DO_defuser, 4, P__0)
extern unsigned char _CPS_ps_DO_defuser[];
#define ps_DO_finddef(P__0,P__1)  pprintf(PostScript, _CPS_ps_DO_finddef, 7, P__0, P__1)
extern unsigned char _CPS_ps_DO_finddef[];
#define ps_finddef(font,usertoken) ps_DO_finddef(font,(usertoken)=psio_getnexttoken(PostScript))
#define ps_DO_scaledef(P__0,P__1,P__2)  pprintf(PostScript, _CPS_ps_DO_scaledef, 9, P__0, P__1, P__2)
extern unsigned char _CPS_ps_DO_scaledef[];
#define ps_scaledef(font,scale,usertoken) ps_DO_scaledef(font,scale,(usertoken) = psio_getnexttoken(PostScript))
#define ps_usetfont(P__0)  pprintf(PostScript, _CPS_ps_usetfont, 3, P__0)
extern unsigned char _CPS_ps_usetfont[];
#endif
