/* DO NOT EDIT THIS FILE.  It contains C->PostScript communication
   definitions that were automatically generated from font_cps.cps */

#define ps_fontinit()  pprintf(PostScript, _CPS_ps_fontinit, 2354)
extern char _CPS_ps_fontinit[];
#define ps_locatefont(P__0,P__1,P__2) ( pprintf(PostScript, _CPS_ps_locatefont, 17, P__2, P__0), ps_checkfor(PostScriptInput, PSIO_WAIT_TAG, P__2) > 0 && (_CPS_RETURN_ps_locatefont(P__1), 1))
#define _CPS_RETURN_ps_locatefont(P__1) pscanf(PostScriptInput,"d", P__1)
extern char _CPS_ps_locatefont[];
#define ps_assignfont(P__0,P__1,P__2,P__3)  pprintf(PostScript, _CPS_ps_assignfont, 23, P__3, P__2, P__1, P__0)
extern char _CPS_ps_assignfont[];
#define ps_uploadfont(P__0,P__1,P__2,P__3,P__4) ( pprintf(PostScript, _CPS_ps_uploadfont, 17, P__4, P__0), ps_checkfor(PostScriptInput, PSIO_WAIT_TAG, P__4) > 0 && (_CPS_RETURN_ps_uploadfont(P__2, P__3, P__1), 1))
#define _CPS_RETURN_ps_uploadfont(P__2, P__3, P__1) pscanf(PostScriptInput,"eed", P__2, P__3, P__1)
extern char _CPS_ps_uploadfont[];
#define ps_uploadfontfamilies(P__0,P__1) ( pprintf(PostScript, _CPS_ps_uploadfontfamilies, 36, P__1), ps_checkfor(PostScriptInput, PSIO_WAIT_TAG, P__1) > 0 && (_CPS_RETURN_ps_uploadfontfamilies(P__0), 1))
#define _CPS_RETURN_ps_uploadfontfamilies(P__0) pscanf(PostScriptInput,"d", P__0)
extern char _CPS_ps_uploadfontfamilies[];
#define ps_get_font_name(P__0,P__1,P__2,P__3) ( pprintf(PostScript, _CPS_ps_get_font_name, 39, P__0, P__1, P__3), ps_checkfor(PostScriptInput, PSIO_WAIT_TAG, P__3) > 0 && (_CPS_RETURN_ps_get_font_name(P__2), 1))
#define _CPS_RETURN_ps_get_font_name(P__2) pscanf(PostScriptInput,"s", P__2)
extern char _CPS_ps_get_font_name[];
#define ps_getint(P__0) (_CPS_RETURN_ps_getint(P__0))
#define _CPS_RETURN_ps_getint(P__0) pscanf(PostScriptInput,"e", P__0)
#define ps_getstring(P__0) (_CPS_RETURN_ps_getstring(P__0))
#define _CPS_RETURN_ps_getstring(P__0) pscanf(PostScriptInput,"s", P__0)
#define ps_usefont(P__0)  pprintf(PostScript, _CPS_ps_usefont, 3, P__0)
extern char _CPS_ps_usefont[];
#ifndef PSMACROS_H
#include <NeWS/psmacros.h>		/* standard cdef macros */
#endif
